using System.Collections.Generic;

namespace RGF
{
    public enum ElementTypeEnum { Read, Write, ReadWrite }

    public static class UDC
    {
        //static collection of all controls used in the scope
        public static List<IUpdatableControl> AllControls { get; set; } = new List<IUpdatableControl>();
    }

    public class ObjectID
    {
        public int ID { get; }
        public ElementTypeEnum Type { get; }

        public ObjectID(int id, ElementTypeEnum type)
        {
            ID = id;
            Type = type;
        }
    }

    public interface IUpdatableControl
    {
        //the list of FWO IDs used in the control
        List<ObjectID> ObjectIDs { get; }

        int ID { get;  }
        int ModNr { get;  } 

        //the ID of the screen the control is located in
        string ScreenKey { get; }

        //the control already has a module number and ID defined in the XAML
        void Setup(string key);

        //the control has and ID but no module number (resuable control valid for multiple modules) 
        void Setup(string key, int modnr);

        //the control is auto-generated by the screen
        void Setup(string key, int modnr, int ID);

        void Update();
    }

}