using System.Collections.Generic;

namespace RGF
{
    public interface IUpdatableControl
    {
        //the list of RGO IDs used in the control
        List<ObjectID> ObjectIDs { get; }

        string ID { get;  }
        int ModNr { get;  } 

        //the ID of the screen the control is located in
        string ScreenKey { get; }

        //the control already has a module number and ID defined in the XAML
        void Setup(string key);

        //the control has an ID but no module number (resuable control valid for multiple modules) 
        void Setup(string key, int modnr);

        //the control is generated by the screen
        void Setup(string key, int modnr, string ID);

        void Update();
    }

}